
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.bryan.ejemploresult.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUMA = 5;
  public static final int MULT = 7;
  public static final int NUMERO_ENTERO = 2;
  public static final int EOF = 0;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int PARENT_C = 4;
  public static final int RESTA = 6;
  public static final int PARENT_A = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO_ENTERO",
  "PARENT_A",
  "PARENT_C",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV"
  };
}

